<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'name' => 'Street Food Burguer Porn',
                'total_price' => 21.00,
                'categories_id' => 1,
                'image' => '../../img/foodPorn.jpg',
                'ubication' => 'Avenida Alemania, 19',
                'capacity' => 100,
                'user_id' => 1,
                'visible' => true, // Nuevo campo
            ],
            [
                'name' => 'La Mafia Se Sienta A La Mesa',
                'total_price' => 35.00,
                'categories_id' => 2,
                'image' => '../../img/Mafia.png',
                'ubication' => 'Calle Luis de Morales, 2',
                'capacity' => 100,
                'user_id' => 2,
                'visible' => true,
            ],
            [
                'name' => 'Maquiavelo',
                'total_price' => 17.00,
                'categories_id' => 3,
                'image' => '../../img/maquiavelo.jpg',
                'ubication' => 'Puente de los Remedios, Puerto de las Delicias',
                'capacity' => 100,
                'user_id' => 3,
                'visible' => true,
            ],
            [
                'name' => 'Blanca Paloma',
                'total_price' => 29.00,
                'categories_id' => 4,
                'image' => '../../img/blancaPaloma.jpg',
                'ubication' => 'Calle San Jacinto, 49',
                'capacity' => 100,
                'user_id' => 4,
                'visible' => true,
            ],
            [
                'name' => 'Río Grande',
                'total_price' => 22.00,
                'categories_id' => 5,
                'image' => '../../img/rioGrande.jpg',
                'ubication' => 'Calle Betis, 69',
                'capacity' => 100,
                'user_id' => 5,
                'visible' => true,
            ],
            [
                'name' => 'Bilio',
                'total_price' => 11.00,
                'categories_id' => 5,
                'image' => '../../img/bilio.jpg',
                'ubication' => 'Avenida de la Innovación, 7/9',
                'capacity' => 100,
                'user_id' => 6,
                'visible' => true,
            ],
            [
                'name' => 'Abades Triana',
                'total_price' => 28.00,
                'categories_id' => 1,
                'image' => '../../img/abades.jpg',
                'ubication' => 'Calle Betis, 69',
                'capacity' => 100,
                'user_id' => 7,
                'visible' => true,
            ],
            [
                'name' => 'Las Dunas',
                'total_price' => 15.00,
                'categories_id' => 2,
                'image' => '../../img/Dunas.jpg',
                'ubication' => 'Calle Flor de Albahaca, 7',
                'capacity' => 100,
                'user_id' => 8,
                'visible' => true,
            ],
            [
                'name' => 'Taberna Bocanegra',
                'total_price' => 15.00,
                'categories_id' => 2,
                'image' => '../../img/bocanegra.jpg',
                'ubication' => 'Avenida Finlandia, SN',
                'capacity' => 100,
                'user_id' => 9,
                'visible' => true,
            ],
            [
                'name' => 'Taberna Coloniales',
                'total_price' => 16.00,
                'categories_id' => 2,
                'image' => '../../img/coloniales.jpg',
                'ubication' => 'Plaza Cristo de Burgos, 19',
                'capacity' => 100,
                'user_id' => 10,
                'visible' => true,
            ],
            [
                'name' => 'Taberna El Arenal',
                'total_price' => 13.00,
                'categories_id' => 2,
                'image' => '../../img/Arenal.jpg',
                'ubication' => 'Calle Almirante Lobo, 2',
                'capacity' => 100,
                'user_id' => 11,
                'visible' => true,
            ],
            [
                'name' => 'Taberna Antonio Romero',
                'total_price' => 20.00,
                'categories_id' => 2,
                'image' => '../../img/antonioRomero.jpg',
                'ubication' => 'Calle Antonia Díaz, 19',
                'capacity' => 100,
                'user_id' => 12,
                'visible' => true,
            ],
            [
                'name' => 'Restaurante San Marco (Santa Cruz, Sevilla)',
                'total_price' => 30.00,
                'categories_id' => 2,
                'image' => '../../img/SanMarco.jpg',
                'ubication' => 'Calle Mesón del Moro, 6',
                'capacity' => 100,
                'user_id' => 13,
                'visible' => true,
            ],
            [
                'name' => 'María Trifulca',
                'total_price' => 32.00,
                'categories_id' => 2,
                'image' => '../../img/mariaTrifulca.jpg',
                'ubication' => 'Pte Triana, Pza Altozano, 1',
                'capacity' => 100,
                'user_id' => 14,
                'visible' => true,
            ],
            [
                'name' => 'Taberna Almazara',
                'total_price' => 12.00,
                'categories_id' => 2,
                'image' => '../../img/almazara.jpg',
                'ubication' => 'Calle Afán de Rivera, 177',
                'capacity' => 100,
                'user_id' => 15,
                'visible' => true,
            ],
            [
                'name' => 'Patio San Eloy (Triana)',
                'total_price' => 16.00,
                'categories_id' => 2,
                'image' => '../../img/SanEloyTriana.jpg',
                'ubication' => 'Calle San Jacinto, 16',
                'capacity' => 100,
                'user_id' => 16,
                'visible' => true,
            ],
            [
                'name' => 'Patio San Eloy (Santa Catalina)',
                'total_price' => 16.00,
                'categories_id' => 2,
                'image' => '../../img/SanEloyStaCatalina.jpg',
                'ubication' => 'Calle Alhóndiga, 14',
                'capacity' => 100,
                'user_id' => 17,
                'visible' => true,
            ],
            [
                'name' => 'Bar Casemiro',
                'total_price' => 16.00,
                'categories_id' => 2,
                'image' => '../../img/casemiro.jpg',
                'ubication' => 'Avenida de Coria, 19',
                'capacity' => 100,
                'user_id' => 18,
                'visible' => true,
            ],
            [
                'name' => 'Amanecer (Alameda de Hércules, Sevilla)',
                'total_price' => 15.00,
                'categories_id' => 2,
                'image' => '../../img/amanecer.png',
                'ubication' => 'Alameda de Hércules, 61',
                'capacity' => 100,
                'user_id' => 19,
                'visible' => true,
            ],
            [
                'name' => 'Avelino',
                'total_price' => 14.00,
                'categories_id' => 2,
                'image' => '../../img/avelino.jpg',
                'ubication' => 'Plaza los andes, SN',
                'capacity' => 100,
                'user_id' => 20,
                'visible' => true,
            ],
            [
                'name' => 'Aderezo',
                'total_price' => 24.00,
                'categories_id' => 2,
                'image' => '../../img/aderezo.jpg',
                'ubication' => 'Avenida Médico Sin Fronteras, 15',
                'capacity' => 100,
                'user_id' => 21,
                'visible' => true,
            ],
        ]);
    }
}